apiVersion: batch/v1
kind: Job
metadata:
  name: box
spec:
  template:
    spec:
      containers:
      - name: box
        image: busybox
        command: ["echo", "cronjob"]
      restartPolicy: Never
  backoffLimit: 4